export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_STATE = 'LOGIN_STATE';
export const REGISTER_STATE = 'REGISTER_STATE';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';

export const INPUT_VALUE_CHANGED = 'INPUT_VALUE_CHANGED';

export const UPDATE_DATA_START = ' UPDATE_DATA_START';
export const UPDATE_DATA_SUCCESS = ' UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = ' UPDATE_DATA_FAIL';

export const REMOVE_FILE = 'REMOVE_FILE';

export const COLUMN_INPUT_VALUE_CHANGED = 'COLUMN_INPUT_VALUE_CHANGED';

export const PARAMS_FOR_FILTERING_CHANGED = 'PARAMS_FOR_FILTERING_CHANGED';

export const OPEN_TABLE = 'OPEN_TABLE';
export const OPEN_PLOT = 'OPEN_PLOT';
export const OPEN_TESTS = 'OPEN_TESTS';
export const OPEN_STATS = 'OPEN_STATS';
export const OPEN_STORYTELLING = 'OPEN_STORYTELLING';
export const OPEN_DASHBOARD = 'OPEN_DASHBOARD';

export const TEST_START = 'TEST_START';
export const TEST_SUCCESS = 'TEST_SUCCESS';
export const TEST_FAIL = 'TEST_FAIL';

export const PREPROCESSING_START = 'PREPROCESSING_START';
export const PREPROCESSING_DATA_SPLIT_SUCCESS = 'PREPROCESSING_DATA_SPLIT_SUCCESS';
export const PREPROCESSING_NORMALIZING_SUCCESS = 'PREPROCESSING_NORMALIZING_SUCCESS';
export const PREPROCESSING_FAIL = 'PREPROCESSING_FAIL';

export const PROCESSING_START_MACHINE_LEARNING = 'PROCESSING_START_MACHINE_LEARNING';
export const PROCESSING_START_DEEP_LEARNING = 'PROCESSING_START_DEEP_LEARNING';
export const PROCESSING_START_TEXT_MINING = 'PROCESSING_START_TEXT_MINING';
export const FIT_SUCCESS = 'FIT_SUCCESS';
export const PREDICT_SUCCESS_MACHINE_LEARNING = 'PREDICT_SUCCESS_MACHINE_LEARNING';
export const PREDICT_SUCCESS_DEEP_LEARNING = 'PREDICT_SUCCESS_DEEP_LEARNING';
export const PREDICT_SUCCESS_TEXT_MINING = 'PREDICT_SUCCESS_TEXT_MINING';
export const PROCESSING_FAIL = 'FIT_FAIL';
export const RESET_TABLE = 'RESET_TABLE';

export const RESET_DATA = 'RESET_DATA';
export const DF_INFO = 'DF_INFO';






