export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';

export const INPUT_VALUE_CHANGED = 'INPUT_VALUE_CHANGED';

export const UPDATE_DATA_START = ' UPDATE_DATA_START';
export const UPDATE_DATA_SUCCESS = ' UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = ' UPDATE_DATA_FAIL';

export const REMOVE_FILE = 'REMOVE_FILE';

export const COLUMN_INPUT_VALUE_CHANGED = 'COLUMN_INPUT_VALUE_CHANGED';

export const PARAMS_FOR_FILTERING_CHANGED = 'PARAMS_FOR_FILTERING_CHANGED';

export const OPEN_TABLE = 'OPEN_TABLE';
export const OPEN_PLOT = 'OPEN_PLOT';
export const OPEN_TESTS = 'OPEN_TESTS';

export const TEST_START = 'TEST_START';
export const TEST_SUCCESS = 'TEST_SUCCESS';
export const TEST_FAIL = 'TEST_FAIL';

export const PREPROCESSING_START = 'PREPROCESSING_START';
export const PREPROCESSING_DATA_SPLIT_SUCCESS = 'PREPROCESSING_DATA_SPLIT_SUCCESS';
export const PREPROCESSING_NORMALIZING_SUCCESS = 'PREPROCESSING_NORMALIZING_SUCCESS';
export const PREPROCESSING_FAIL = 'PREPROCESSING_FAIL';

export const PROCESSING_START = 'PROCESSING_START';
export const FIT_SUCCESS = 'FIT_SUCCESS';
export const PREDICT_SUCCESS = 'PREDICT_SUCCESS';
export const PROCESSING_FAIL = 'FIT_FAIL';






