export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';

export const INPUT_VALUE_CHANGED = 'INPUT_VALUE_CHANGED';

export const UPDATE_DATA_START = ' UPDATE_DATA_START';
export const UPDATE_DATA_SUCCESS = ' UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = ' UPDATE_DATA_FAIL';

export const REMOVE_FILE = 'REMOVE_FILE';

export const COLUMN_INPUT_VALUE_CHANGED = 'COLUMN_INPUT_VALUE_CHANGED';

export const PARAMS_FOR_FILTERING_CHANGED = 'PARAMS_FOR_FILTERING_CHANGED';

