# Generated by Django 2.2.4 on 2019-09-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
