# Generated by Django 2.2.4 on 2019-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_backend', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
