# Generated by Django 2.2.5 on 2020-02-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_backend', '0005_editorfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorFiles',
            new_name='EditorFile',
        ),
    ]
