# Generated by Django 2.2.5 on 2020-03-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_backend', '0006_auto_20200227_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorFile',
            new_name='PlotFile',
        ),
    ]
