# Generated by Django 2.2.5 on 2020-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_backend', '0007_auto_20200304_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotfile',
            name='file',
            field=models.ImageField(upload_to='plot/files'),
        ),
    ]
